services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        tags:
            - { name: ws.widget }

    WS\Site\Widget\:
        resource: '../../Widget/*'
